### ISSUE TITLE
LidarVolume int cast from double

### ISSUE THREAD

**Issue by arezaii** [BoiseState-AdaptLab/adapt-lidar-tools#132]
There are some casts from double to int (lines 48, 49, 50 of LidarVolume.cpp) and some functions that cast ints from double (gps_to_voxel_x and gps_to_voxel_y). 

I am documenting this because I found a possibility for overflow when troubleshooting #78

**Comment by jaredwhite547** [comment]
Changed to `ceil` and `floor` where applicable, both in `master` and `TemplateRefactoring`
