### ISSUE TITLE
Standard deviation calculation 

### ISSUE THREAD

**Issue by FloCiaglia** [BoiseState-AdaptLab/adapt-lidar-tools#182]
Nayani's way of calculating the standard deviation uses a sample of the population rather than the entire population. We needed to use her method.

**Comment by cathieO** [comment]
Nayani uses a calculation for a subset of the population. This is due to availability in matlab.
We are switching to that formulation (n+1) rather than (n).

**Comment by cathieO** [comment]
Aaron will add 3-4 unit tests to verify that the calculation is working.

**Comment by Aaron3154518** [comment]
Skewness and Kurtosis also need to have the N-1 instead of N

**Comment by Aaron3154518** [comment]
I recalculated the std dev, skewness, and kurtosis using our new equation. I also changed the expected value for the 1 peak tests to the NO_DATA value to make sure NaN and Infinity values were being accounted for and corrected. All tests passed.
