### ISSUE TITLE
Check convergence conditions for Gaussian Fitting

### ISSUE THREAD

**Issue by cathieO** [BoiseState-AdaptLab/adapt-lidar-tools#184]
I'd like us to stop iterating faster, rather than doing several iterations with no change.

**Comment by Aaron3154518** [comment]
Acceptable error is 10^-8 which is too small considering our peak amplitudes are usually greater than 100. We should raise the acceptable error.

**Comment by Aaron3154518** [comment]
With an error 10^8 this waveform took 10 iterations to give us this

**Comment by Aaron3154518** [comment]
![image](https://user-images.githubusercontent.com/43934996/62428657-0deba080-b6c1-11e9-8b3c-3e112b8aeb34.png)

**Comment by Aaron3154518** [comment]
Setting the error to 10^-8 * max_value took 7 iterations to give us this

**Comment by Aaron3154518** [comment]
![image](https://user-images.githubusercontent.com/43934996/62428664-2bb90580-b6c1-11e9-9630-47ee891957c8.png)

**Comment by Aaron3154518** [comment]
This essentially shows that our error parameters for the gaussian fitting are too small and cause the fitting process to perform iterations which change points on our model by at most 10^-5

**Comment by Aaron3154518** [comment]
Additionally and error of 10^-8 took 4min 8sec on a file of about 5MB while and error of 10^-8 * max_val took 2min 38sec

**Comment by Aaron3154518** [comment]
The following times are using a different version of our code. Due to work being done in GaussianFitter.cpp at the time, the 5MB file took 4min to run with e-08 tolerance however with the version of GaussianFitter.cpp that I used to get the following information, the 5MB file ran in 19 seconds with e-08 tolerance.

**Comment by Aaron3154518** [comment]
1) Tolerance of 1e-08, Run Time 19sec
2) Tolerance of max*1e-02, Run Time 3.6sec
3) Tolerance of max*1e-01, Run Time 3.3sec

They all produced extremely similar data with an average difference of 0.0049 between tolerances 1 and 2 and an average difference of 0.0064 between tolerances 2 and 3.

**Comment by Aaron3154518** [comment]
The 1GB file which normally takes 32min to complete instead took 9min 44sec to complete and had an average difference of 0.0036 from the 32min file.
