### ISSUE TITLE
Why is GaussianFitter compiled differently than everything else?

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#214]
The command to make most every other object is like this:
```
$(CXX) -c -o $@ $^ $(CFLAGS) -L$(PULSE_DIR)/lib
```
With the ones that use gdal also calling -gdal.

The file does a good job at explaining itself except with Gaussian Fitter:
```
$(CXX) -std=c++11 -g -fpermissive -c -o $@ $^ -lm \
    -lgsl -lgslcblas
```

One thing I looked up was -fpermissive. From the [documentation](http://gcc.gnu.org/onlinedocs/gcc-4.0.4/gcc/C_002b_002b-Dialect-Options.html#index-fpermissive-140):
"-fpermissive: Downgrade some diagnostics about nonconformant code from errors to warnings. Thus, using -fpermissive will allow some nonconforming code to compile."
**Why are we using this? That seems bad.**

-lm is just linking the math library, same as -gsl and -lgslcblas, I assume, but for gsl.

Also worth noting is that a lot of important C++ compiler parameters are missing because it isn't calling $(CFLAGS) or $(CXXFLAGS), like -Wall & -Wextra. I can't help but wonder if some of the other flags in there are also important.
**So, second question: Why shouldn't GaussainFitter be compiled using the $(CFLAGS) option, or the $(CXXFLAGS) option?**

Anyways, I just noticed this while I've been implementing the change to update everything to the C++11 standard and wanted to be sure I mentioned it, so we can add the reasoning to the comments in the makefile.

**Comment by jaredwhite547** [comment]
No longer compiled differently in `TemplateRefactoring`
