### ISSUE TITLE
Research how to implement spdlog

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#224]
I need to know how to determine how to install and use spdlog in our software.

Goals:
- Understand how to install in repo, so it can be integrated into our software
- Understand how to perform basic operations with the logger (like logging a message, as crazy as it sounds)
- Feel confident I can integrate this into our project

**Comment by SpencerFleming** [comment]
Done because we're not implementing it

**Comment by cathieO** [comment]
present a code review in next meeting.
