### ISSUE TITLE
Finish comments for each class

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#244]
There are comments in the detailed class diagram that help people understand what each file does. These need to:

- [x] Exist for each class
- [ ] Make sense

**Comment by SpencerFleming** [comment]
@Aaron3154518 When you get back, you should take a look at the comments I put in there and see if they make sense.

**Comment by SpencerFleming** [comment]
In the class diagram I mean

**Comment by Aaron3154518** [comment]
I went through the class diagram and responding your comments as well as making a couple edits. You might want to double check and make sure it all still makes sense.

**Comment by Aaron3154518** [comment]
I apologize for taking so long to do this

**Comment by rvishnkr** [comment]
> I apologize for taking so long to do this

No worries. You're good!
