### ISSUE TITLE
Why do we use -lpthread instead of -pthread?

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#251]
I noticed we use -lpthread in our Makefile. Supposedly it is recommended that we use -pthread instead unless we have a specific reason to use -lpthread instead. I wanted to know why, or if we can change it to improve our Makefile.

**Comment by jaredwhite547** [comment]
Both makefiles (new in `TemplateRefactoring`, and current in `master`) use `-lpthread`
