### ISSUE TITLE
Fixing all magic numbers

### ISSUE THREAD

**Issue by cathieO** [BoiseState-AdaptLab/adapt-lidar-tools#282]
All magic numbers need to be fixed - this may mean adding them as a parameter and it may mean writing the code differently.

**Comment by SpencerFleming** [comment]
From #267:

> Magic Numbers: (Line numbers are subject to changes slightly)
> Min/Max Peak Amplitude 497-498
> Noise Level (scaled vs. set) 634-649
> Gaussian Fitter Error Tolerances (xtol, ftol, and gtol) 275-277
> Default Pulse Width 754-763
> Max Number of Iterations 299-300

> Noise level is 6 based on the literature of the lidar instrument.
> This value should be eventually converted into an input option.

For reference.

**Comment by SpencerFleming** [comment]
I'm going to make these parameters into public members of Gaussian Fitter (or wherever they are used for that matter, if it would be inappropriate to put them in Gaussian Fitter). Then it will be easy to add support for input options later.
