### ISSUE TITLE
exit( ) called by FlightLineData::getNextPulse

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#291]
exit is called three times by this function:
- When there is no next pulse to be read
- When the type of the first sampling isn't outgoing
- When the type of the second sampling isn't returning

My proposed solution to this is to simply return an empty PulseData object that will resolve to "NO_DATA" when fitted, and use spdlog to report a critical error. There is a good chance that the rest of the data is salvageable if this happens.

**Comment by SpencerFleming** [comment]
I changed everything like described above and all unit tests still pass.

**Comment by 7thfleet** [comment]
Need to return a value that can indicate an error.

**Comment by jaredwhite547** [comment]
Need to return a value that can indicate an error.
