### ISSUE TITLE
Unit Test Bugs

### ISSUE THREAD

**Issue by cathieO** [BoiseState-AdaptLab/adapt-lidar-tools#314]
bin/PulseData_unittests
Running main() from deps/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PulseDataTest
[ RUN      ] PulseDataTest.testSetterGetter
src/PulseData_unittests.cpp:63: Failure
Expected equality of these values:
  streamData
    Which is: "\nOutgoing:\n\n\tindices:\n\t0 1 2 \n\tamplitudes:\n\t34 45 67 \n\nReturning Wave:\n\n\tindices:\n\t0 1 2 \n\tamplitudes:\n\t76 65 43 "
  realStream
    Which is: "\nOutgoing:\n\n\tindices:\n\t0 1 2 \n\tamplitudes: \n\t34 45 67 \n\nReturning Wave:\n\n\tindices:\n\t0 1 2 \n\tamplitudes:\n\t76 65 43 "
With diff:
@@ -4,5 +4,5 @@
 \tindices:
 \t0 1 2 
-\tamplitudes:
+\tamplitudes: 
 \t34 45 67 
 

[  FAILED  ] PulseDataTest.testSetterGetter (0 ms)
[----------] 1 test from PulseDataTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PulseDataTest.testSetterGetter

 1 FAILED TEST
make: [test] Error 1 (ignored)

**Comment by SpencerFleming** [comment]
It looks like there was an extra space in the unit test somehow, it looks like it was an accident. Removing that one space character and recompiling made the test pass.
