### ISSUE TITLE
Make noise_level a command line argument

### ISSUE THREAD

**Issue by jaredwhite547** [BoiseState-AdaptLab/adapt-lidar-tools#332]
Currently hardcoded in LidarDriver.cpp

**Comment by jaredwhite547** [comment]
Implemented: 00216b47ba4f20c11524ba2a85143f1d21b55481

**Comment by Aaron3154518** [comment]
Add a try/catch block around the conversion from the noise level argument to an integer

**Comment by Aaron3154518** [comment]
Set default noise level to 6

**Comment by jaredwhite547** [comment]
Implemented: 167b7a9278cc82b55b12637e578c1a73ad442fcc
