### ISSUE TITLE
Default SPDLOG level should be critical

### ISSUE THREAD

**Issue by Aaron3154518** [BoiseState-AdaptLab/adapt-lidar-tools#333]
We would like the default logging level for spdlog to be Critical errors only.

**Comment by Aaron3154518** [comment]
The average user should see message that report what high level task is being completed (e.g."Processing something.pls"). However this information is in the info level of spdlog and thus is not reported when set to the critical level. We should either set the default level to info or find another way to present this information.

**Comment by cathieO** [comment]
Let's change this so that the default is info

**Comment by Aaron3154518** [comment]
We have a statement for when peak width is less than zero which is at the warning level that prints a lot.
