### ISSUE TITLE
Change logging level through the makefile

### ISSUE THREAD

**Issue by FloCiaglia** [BoiseState-AdaptLab/adapt-lidar-tools#334]
When we change logging level we should do that through the makefile.

**Comment by Aaron3154518** [comment]
We have to set the logging level at compile-time

**Comment by jaredwhite547** [comment]
May be of use:
https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html 
https://www.rapidtables.com/code/linux/gcc/gcc-d.html
