### ISSUE TITLE
Log situations where we use a default value

### ISSUE THREAD

**Issue by Aaron3154518** [BoiseState-AdaptLab/adapt-lidar-tools#337]
We would like to document, through the logger, situations where our code failed to get an acceptable value and had to resort to using a default.

**Comment by jaredwhite547** [comment]
With respect to guess_peaks

**Comment by SpencerFleming** [comment]
I just made it so when the guess peak width reverts to the default upon realizing it is negative, it logs a message. I was trying to find other situations where a log message like this would be necessary but can't find any at the moment.
