### ISSUE TITLE
Fitting Info is redundant and no longer needs to be in our program.

### ISSUE THREAD

**Issue by Aaron3154518** [BoiseState-AdaptLab/adapt-lidar-tools#353]
fitting_info.cpp as well as FittingInfoDriver.cpp/.hpp should a some point be removed from the project. They are not meant to be permanent fixtures of our tool set and do not have unittests. No other files have dependencies on them and they are safe to delete. They were simply created to quickly provide information about Gaussian Fitting.

**Comment by SpencerFleming** [comment]
DELETE STUFF ACCOC. W. THIS
