### ISSUE TITLE
Converting std::vector to struct

### ISSUE THREAD

**Issue by brandonechols97** [BoiseState-AdaptLab/adapt-lidar-tools#357]
Improving performance by removing `std::vector` usage in areas that call `push_back`. This change is to use a struct that contains an array with size and max capacity instead. Due to `push_back` allocating memory every time a new element is added.

**Comment by brandonechols97** [comment]
![prof_getNextPulse](https://user-images.githubusercontent.com/25675541/68978801-10c65900-07b9-11ea-99a5-11e7425bedb0.png)
![prof_before_getNextPulse](https://user-images.githubusercontent.com/25675541/68978815-1623a380-07b9-11ea-9047-7341325b2b66.png)

**Comment by jaredwhite547** [comment]
FYI you can prevent std::vector from reallocating by simply calling [reserve](https://en.cppreference.com/w/cpp/container/vector/reserve) with the size you expect. No more allocations will occur unless this size is exceeded.

**Comment by jaredwhite547** [comment]
Reverted. New refactoring makes this unneeded.
