### ISSUE TITLE
Parameter 7 to routine source_gemv_r.h was incorrect 

### ISSUE THREAD

**Issue by arezaii** [BoiseState-AdaptLab/adapt-lidar-tools#95]
The geotiff-driver is crashing when trying to process very large files. 

**Steps to Reproduce:**
1. try to process a very large file, such as 160926_190929_2.pls
2. about 3.5 minutes into processing, the program crashes

**Actual Results:**
```
Processing  etc/160926_190929_2.pls
Finding peaks with gaussian fitting
Parameter 7 to routine source_gemv_r.h was incorrect
Aborted (core dumped)
```

**Expected Results:**
No crash, output products produced

**Other notes:**
Things to investigate:
- is it always in the same place in the file?
- is there something different about the data in these (newer) files vs. the test/dev files?
- is there a code flaw in the program (overflow, underflow, array out of bounds)?
- could it be a memory leak or invalid read?

**Comment by rvishnkr** [comment]
Added a check  `peakCount == 0` soon after the `guess_peaks(...)` call
